FROM node:alpine AS build
WORKDIR /app
COPY ./package*.json ./
# RUN npm ci --production && npm clean cache --force
RUN npm install
COPY . .
RUN npm run build

FROM nginx:latest
# FROM https:alpine
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
# CMD npm install -g serve

# CMD serve -s build
CMD ["nginx", "-g", "daemon off;"]